#!/bin/sh

set -u

if [ "$#" = 0 ]
then
    cat <<END
add: for each \$path given as an argument, do the following:
* If \$HOME/\$path exists and is not a symlink or a regular file, return
  an error.
* If \$DOT/\$path exists and is not a regular file, return an error.
* If \$HOME/\$path exists and \$DOT/\$path does not, move the former to
  the latter.
* Delete \$HOME/\$path if it exists and replace it with a symlink to
  \$DOT/\$path.
* Make \$DOT/\$path an empty file if it does not exist.
END
    exit
fi

while [ "$#" != 0 ]
do
    home_path="$HOME/$1"
    dot_path="$DOT/$1"

    if [ -e "$home_path" ] && [ ! -f "$home_path" ] && [ ! -L "$home_path" ]
    then
        echo "Error: $home_path exists and is not a symlink or regular file" >&2
        exit 1
    fi

    if [ -e "$dot_path" ] && [ ! -f "$dot_path" ]
    then
        echo "Error: $dot_path exists and is not a regular file" >&2
        exit 1
    fi

    mkdir -p "$(dirname "$home_path")"
    mkdir -p "$(dirname "$dot_path")"

    [ -e "$home_path" ] && [ ! -e "$dot_path" ] && mv "$home_path" "$dot_path"

    [ -e "$home_path" ] && rm -f "$home_path"
    ln -s "$dot_path" "$home_path"

    [ ! -e "$dot_path" ] && touch "$dot_path"

    shift
done
