#!/bin/sh

set -eu

if [ "$#" = 0 ]
then
    cat <<END
add: for each $path given as an argument, do the following:
* If $HOME/$path exists and is not a symlink or a regular file, return
  an error.
* If $DOT/$path exists and is not a regular file, return an error.
* If $HOME/$path exists and $DOT/$path does not, move the former to
  the latter.
* Delete $HOME/$path if it exists and replace it with a symlink to
  $DOT/$path.
* Make $DOT/$path an empty file if it does not exist.
END
    exit
fi

while [ "$#" != 0 ]
do
    path="$1"
    echo "$path"
    shift
done
