#!/bin/sh

set -eu
cd "$(dirname "$0")"

for dotfile in $(fd --strip-cwd-prefix --hidden --type=file --exclude ./LICENSE --exclude ./README.md --exclude ./.gitignore --exclude ./install)
do
    mkdir -p "$(dirname "$dotfile")"
    ln -sf "$dotfile" "$HOME/$dotfile"
done
