#!/bin/sh

set -eu
cd "$(dirname "$0")"

for dotfile in $(fd --strip-cwd-prefix --hidden --type=file --exclude LICENSE --exclude README.md --exclude .gitignore --exclude install)
do
    mkdir -p "$(dirname "$HOME/$dotfile")"
    ln -sf "$PWD/$dotfile" "$HOME/$dotfile"
done

chmod go= "$HOME/.config/gnupg"
mkdir -p "$HOME/.local/state/bash"
