#!/usr/bin/env bash

set -euo pipefail

sudo add-apt-repository ppa:neovim-ppa/stable -y
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt-get update

sudo apt-get install \
    neovim git fzf ripgrep tldr neomutt python3-pip

sudo apt autoremove
